catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('languages/', views.LanguageListView.as_view(), name='languages'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

urlpatterns += [
    path('borrowedbooks/', views.LoanedBooksListView.as_view(), name='all-borrowed'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
    path('book/<int:pk>/deconjugate/', views.book_deconjugated, name='book_deconjugated'),
]

learnlan/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import auth


urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('user/', include('user.urls', namespace='user')),
]

#Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = 'user'

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns = [
    # path('user_settings/', views.UserSettingsDetailView.as_view(), name='user_settings-detail'),
    path('user_settings/', views.user_settings, name='user_settings'),
    path('user_settings/<int:pk>/update/', views.UserSettingsUpdate.as_view(), name='user_settings_update'),
]

catalog/forms.py
import datetime
from catalog.models import Book

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


from django.forms import ModelForm
from catalog.models import BookInstance

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ('translation_problems',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from catalog.forms import BookForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from catalog.models import Book, Author, BookInstance, Genre, Language
from catalog.init_db import make_lrc_files
import datetime
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookModelForm
import os
from django.conf import settings
from text_parse import deconjugate
from django.views import generic
from django.urls import resolve

    # @login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    num_authors_j = Author.objects.filter(first_name__contains='J').count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 20
    # context_object_name = 'my_book_list'   # your own name for the list as a template variable
    # queryset = Book.objects.all()[:5] # Get 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location


class BookDetailView(generic.DetailView):
    model = Book
    fields = ['title', 'author', 'isbn', 'source_language', 'translation_language',
              'genre', 'text']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lrc_archive = 'no subtitles'
        if self.object.lrc_archive:
            lrc_archive = os.path.basename(self.object.lrc_archive.path)
        context['lrc_archive'] = lrc_archive
        return context


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 1
    # context_object_name = 'my_book_list'   # your own name for the list as a template variable
    # queryset = Book.objects.all()[:5] # Get 5 books containing the title war
    # template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location


class LanguageListView(generic.ListView):
    model = Language


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        obj = kwargs['object']
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context.update({'next': Author.objects.filter(id__gt=obj.id).order_by('id').first()})
        context.update({'previous': Author.objects.filter(id__lt=obj.id).order_by('id').last()})
        # context.update({'next': Author.get_next_by_id(obj)})
        return context


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    # context_object_name = 'my_book_list'   # your own name for the list as a template variable

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed.html'
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'
    # context_object_name = 'my_book_list'   # your own name for the list as a template variable

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            # book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        # form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


def app_name(request):
    return request.resolver_match._func_path.split('.')[0]


@permission_required('catalog.can_mark_returned')
def book_deconjugated(request, pk):
    book = get_object_or_404(Book, pk=pk)
    parse_js = f'<script src="{settings.STATIC_URL + app_name(request) + "/js/parse.js"}"></script>'
    context = {
        'book': book,
        'scripts': [settings.JQUERY_URL, settings.VUE_URL, parse_js],
    }
    print(book.text_deconjugated)
    return render(request, 'catalog/book_deconjugated.html', context=context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    success_url = reverse_lazy('authors')


from django.utils.safestring import mark_safe


def form_valid_bookupdate(self, form):
    self.object = Book(sound=self.get_form_kwargs().get('files').get('sound', None))
    self.object = form.save(commit=True)
    book = self.object
    book.text_deconjugated = deconjugate(book.text, book.source_language)
    if book.translate_on_update:
        from catalog.init_db import translate_book
        book.text_with_translation, translate, book.translation_problems, book.sound = \
            translate_book(book, self.request.user, True)
    lrc_archive = make_lrc_files(book)
    lrc_archive = lrc_archive.replace(os.path.join(settings.MEDIA_ROOT, ''), '')
    book.lrc_archive = lrc_archive
    book.save()
    return super(type(self), self).form_valid(form)


class BookCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = BookForm

    def form_valid(self, form):
        return form_valid_bookupdate(self, form)


class BookUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = BookForm

    def form_valid(self, form):
        return form_valid_bookupdate(self, form)


class BookDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load common_tags %}
</head>
<body>
    {% if request.user %}
        <li>You are logged in as {{ request.user }}</li>
    {% else %}
        <li>You are not logged in </li>
    {% endif %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li><a href="{% url 'languages' %}">All languages</a></li>
            <p></p>

           {% if user.is_authenticated %}
             <li>User: {{ user.get_username }}</li>
             <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
             <li><a href="{% url 'user:user_settings' %}">My Settings</a></li>
             <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
           {% else %}
             <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
           {% endif %}

           {% if perms.catalog.can_mark_returned %}
            <p></p>
            Staff
             <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
           {% endif %}
          </ul>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}
        {% block pagination %}
          {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
    {% autoescape off %}
    {% include_scripts %}
    {% endautoescape %}
</body>
</html>

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
<title>My Local Library</title>
{% endblock %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LearnLan, a website created to help you learn languages by listening to books voiced
    sentence by sentence in parallel with translation to your native language!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Authors containing J:</strong> {{ num_authors_j }}</li>
  </ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}